/*
 * Created on 18/10/2008
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */

package com.antiaction.classfile.methods;

import com.antiaction.classfile.Bits;
import com.antiaction.classfile.ClassFileException;
import com.antiaction.classfile.ClassFileState;
import com.antiaction.classfile.attributes.Attribute_Code;
import com.antiaction.classfile.attributes.Attribute_Deprecated;
import com.antiaction.classfile.attributes.Attribute_Exceptions;
import com.antiaction.classfile.attributes.Attribute_Signature;
import com.antiaction.classfile.attributes.Attribute_Synthetic;
import com.antiaction.classfile.attributes.Attributes;
import com.antiaction.classfile.constantpool.ConstantPool_Utf8;

public class Method {

	public static final int ACC_PUBLIC = 0x0001;		// Declared public; may be accessed from outside its package.
	public static final int ACC_PRIVATE = 0x0002;		// Declared private; accessible only within the defining class.
	public static final int ACC_PROTECTED = 0x0004;		// Declared protected; may be accessed within subclasses.
	public static final int ACC_STATIC = 0x0008;		// Declared static.
	public static final int ACC_FINAL = 0x0010;			// Declared final; must not be overridden.
	public static final int ACC_SYNCHRONIZED = 0x0020;	// Declared synchronized; invocation is wrapped in a monitor lock.
	public static final int ACC_BRIDGE = 0x0040;		// A bridge method, generated by the compiler.
	public static final int ACC_VARARGS = 0x0080;		// Declared with variable number of arguments.
	public static final int ACC_NATIVE = 0x0100;		// Declared native; implemented in a language other than Java.
	public static final int ACC_ABSTRACT = 0x0400;		// Declared abstract; no implementation is provided.
	public static final int ACC_STRICT = 0x0800;		// Declared strictfp; floating-point mode is FP-strict.
	public static final int ACC_SYNTHETIC = 0x1000;		// Declared synthetic;
	//public static final int ACC_ = ;
  
	public static final int METHOD_ACCESS_FLAGS_MASK = ACC_PUBLIC | ACC_PRIVATE | ACC_PROTECTED | ACC_STATIC | ACC_FINAL | ACC_SYNCHRONIZED | ACC_BRIDGE | ACC_VARARGS | ACC_NATIVE | ACC_ABSTRACT | ACC_STRICT | ACC_SYNTHETIC;

	public int access_flags;

	public boolean bAbstract = false;

	public int name_index;
	public ConstantPool_Utf8 name_cp;
	public String name;

	public int descriptor_index;
	public ConstantPool_Utf8 descriptor_cp;
	public String descriptor_string;

	public Attributes attributes;

	public Attribute_Code codeAttr = null;

	public Attribute_Deprecated deprecatedAttr = null;

	public Attribute_Exceptions exceptionsAttr = null;

	public Attribute_Synthetic syntheticAttr = null;

	public Attribute_Signature signatureAttr = null;

	public void validate_access_flags(ClassFileState cfs) throws ClassFileException {
		// Check against supported access flags.
		if ( (access_flags & ~METHOD_ACCESS_FLAGS_MASK) != 0 ) {
			throw new ClassFileException( "Invalid method access flags: 0x" + Integer.toHexString( access_flags & ~METHOD_ACCESS_FLAGS_MASK ) );
		}

		// debug
		//System.out.println( "Method: " + name );

		if ( cfs.cf.bClass ) {
			if ( name.startsWith( "<" ) & name.endsWith( ">" ) ) {
				if ( "<clinit>".compareTo( name ) == 0 ) {
				}
				else if ( "<init>".compareTo( name ) == 0 ) {
				}
				else {
					throw new ClassFileException( "No" );
				}
			}
			else {
				if ( Bits.bitstobits[ access_flags & (ACC_PUBLIC | ACC_PRIVATE | ACC_PROTECTED) ] > 1 ) {
					throw new ClassFileException( "Invalid class method access flags: 0x" + Integer.toHexString( access_flags & (ACC_PUBLIC | ACC_PRIVATE | ACC_PROTECTED) ) + " (0x" + Integer.toHexString( access_flags ) + ")" );
				}
				if ( (access_flags & ACC_ABSTRACT) == ACC_ABSTRACT ) {
					bAbstract = true;
					if ( !cfs.cf.bAbstract ) {
						throw new ClassFileException( "Method not declared in abstract class" );
					}
					if ( (access_flags & (ACC_PRIVATE | ACC_STATIC | ACC_FINAL | ACC_SYNCHRONIZED | ACC_NATIVE | ACC_STRICT)) != 0 ) {
						throw new ClassFileException( "Invalid class abstract method access flags: 0x" + Integer.toHexString( access_flags & (ACC_PRIVATE | ACC_STATIC | ACC_FINAL | ACC_SYNCHRONIZED | ACC_NATIVE | ACC_STRICT) ) + " (0x" + Integer.toHexString( access_flags ) + ")" );
					}
				}
			}
		}
		else if ( cfs.cf.bInterface ) {
			if ( name.startsWith( "<" ) & name.endsWith( ">" ) ) {
				if ( "<clinit>".compareTo( name ) == 0 ) {
				}
				else {
					throw new ClassFileException( "No" );
				}
			}
			else {
				if ( (access_flags & ( ACC_PUBLIC | ACC_ABSTRACT )) != ( ACC_PUBLIC | ACC_ABSTRACT ) ) {
					throw new ClassFileException( "Invalid interface method access flags combination: 0x" + Integer.toHexString( access_flags & ( ACC_PUBLIC | ACC_ABSTRACT ) ) + " (0x" + Integer.toHexString( access_flags ) + ")" );
				}
				if ( (access_flags & ~( ACC_PUBLIC | ACC_ABSTRACT | ACC_BRIDGE | ACC_VARARGS | ACC_SYNTHETIC )) != 0 ) {
					throw new ClassFileException( "Invalid interface method access flags combination: 0x" + Integer.toHexString( access_flags & ~( ACC_PUBLIC | ACC_ABSTRACT | ACC_BRIDGE | ACC_VARARGS | ACC_SYNTHETIC ) ) + " (0x" + Integer.toHexString( access_flags ) + ")" );
				}
			}
		}
		else {
			throw new ClassFileException( "Unknown method access flags combination: 0x" + Integer.toHexString( access_flags ) );
		}
	}

}
